model:
  arch: minigpt_3d

#  # vit encoder
#  image_size: 448
#  drop_path_rate: 0
#  use_grad_checkpoint: False
#  vit_precision: "fp16"
#  freeze_vit: True

  # generation configs
  prompt: ""

  llama_model: "./params_weight/Phi_2"
  lora_r: 64
  lora_alpha: 16
  pc_encoder_backend: "uni3d"
  uni3d_ckpt_path: "./minigpt4/models_new/uni3d/weights/uni3dtiny/model.pt"
  uni3d_timm_model: "eva02_tiny_patch14_224"
  uni3d_drop_path_rate: 0.2


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 448
        eval:
          name: "blip2_image_eval"
          image_size: 448
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
